### ISSUE TITLE
the skype emotes plugin needs a bit of fixing

### ISSUE THREAD

**Issue by albert-softie** [Bluscream/BetterDiscord-Plugins#1]
with the new betterdiscord update, they added a new emote menu that injects itself into the new discord emoji menu. however, as of this update, the skype emotes section does not show up in the new emote menu (although they still show up if you type them in manually). do you think you could fix this?

**Comment by Bluscream** [comment]
Sadly i'm not the creator of the plugin.

You should try to contact the authors: "megamit & Decorater" on https://discordapp.com/invite/0Tmfo5ZbORCRqbAd
